### ISSUE TITLE
Please write a template for VB.NET

### ISSUE THREAD

**Issue by Audiopolis** [neo-project/examples#2]
I've tried everything I can think of to create a VB.NET version of the C# template, but I always end up with something like this in the output:

1>CONVERTTASK : Convert error : System.Exception: unknown call:System.String ExternalTest.TestFunctions::Main()
1>     at Neo.Compiler.MSIL.ModuleConverter._ConvertCall(OpCode src, AntsMethod to)
1>     at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, AntsMethod to)
1>     at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, AntsMethod to)
1>     at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in)
1>     at Neo.Compiler.Program.Main(String[] args)

**Comment by erikzhang** [comment]
It has been done in https://github.com/neo-project/neo-devpack-dotnet/commit/2453bde48dd44afeb23c9103104901443111387d
Update your plugin and compiler before trying it.
