### ISSUE TITLE
the Oracle Demo contract return "ProtocolNotSupported" error

### ISSUE THREAD

**Issue by cloud8little** [neo-project/examples#39]
https://raw.githubusercontent.com/neo-project/examples/master/csharp/Oracle/example.json return text/plain type response, default is application/json type.

**Comment by shargon** [comment]
It's not a valid response...

**Comment by hal0x2328** [comment]
The error code would probably be less confusing if it were called `ContentTypeNotSupported` instead of `ProtocolNotSupported`.

**Comment by cloud8little** [comment]
> The error code would probably be less confusing if it were called `ContentTypeNotSupported` or `ResponseContentTypeNotSupported` instead of `ProtocolNotSupported`.

currently only https is supported, if use http request type, it is also ProtocolNotSupported error type, it may be not accurate to call it ContentTypeNotSupported or ResponseContentTypeNotSupported, then it should be better to add another new type called ContentTypeNotSupported.
